name: Update Repository Visibility

on:
  workflow_dispatch:

jobs:
  update-visibility:
    runs-on: ubuntu-latest
    steps:
      - name: Update repository visibility
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              private: false
            })